version: "3"

server:
  command: "php public/index.php"
grpc:
  listen: tcp://0.0.0.0:9001
  proto:
    - "./schema/auth.proto"
    - "./schema/author.proto"

  pool:
    num_workers: 2
    command: "php src/Infrastructure/Grpc/GrpcWorker.php"

http:
  address: "0.0.0.0:8080"
  pool:
    num_workers: 2
